### ISSUE TITLE
Footprints for tactile switches

### ISSUE THREAD

**Issue by gaexpa1** [ziteh/calcite#1]
The footprint SW_SPST_B3U-1000P is incompatible with the TS-1064S-A1B2-D4.
B3U-1000P-B?

**Comment by ziteh** [comment]
You are right, this footprint without boss, the correct part should be B3U-1000P or TS-1064S***A***

**Comment by ziteh** [comment]
Fixed in 1e7c8a413dfbfd1b928f15de38907081ed8602bb

Close inactive issue, and please feel free to reopen it if needed : )
